import streamlit as st

from utils.display import sidebar, header_logo, real_time_word_count
from utils.machine_learning import load_model, make_prediction


st.set_page_config(
    page_title="Predict GPT",
    page_icon="🔮"
)


with open("app/css/styles.css") as f:
    st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)

with st.container():
    sidebar()

with st.container():
    header_logo()

with st.container():
    st.markdown("""
                # PREDIKSI TEKS GPT
                <div style="text-align: justify">
                    Berdasarkan hasil penelitian, t5_fullMerg menjadi model dengan performa paling baik dengan menjadi peringkat kedua
                    dalam hal akurasi dan menjadi peringkat pertama dalam nilai F1-Score. Maka dari itu, fitur prediksi yang digunakan
                    pada aplikasi kali ini menggunakan model tersebut.
                </div><br>
                
                ### 📖 Petunjuk Penggunaan
                Untuk memeriksa sebuah teks adalah hasil buatan mesin/kecerdasan buatan atau bukan, silahkan ikuti petunjuk berikut:
                1. 📄 Masukkan abstrak penelitian atau teks apapun dalam bentuk paragraf.
                2. 📝 Teks yang dimasukkan harus berbahasa Inggris.
                3. 🔢 Teks harus memiliki banyak kata minimal 100 kata.
                4. 🔍 Tekan tombol periksa untuk memulai pengecekan.
                5. ⏳ Silahkan tunggu hasil pemeriksaan.
    """,unsafe_allow_html=True)

    st.divider()

model, tokenizer = load_model()

input_text = st.text_area('Masukkan teks untuk diprediksi')

word_count = real_time_word_count(input_text)
st.write(f"Jumlah Kata: {word_count}")

if st.button('Periksa'):
    word_count = len(input_text.split())

    if word_count >= 100:
        with st.spinner('Wait For Prediction 😉'):
            prediction_value = make_prediction(input_text, model, tokenizer)

        prediction_percentage = prediction_value * 100
        st.markdown(
            f'<div class="result-box">Generated by Machine {prediction_percentage:.2f}%</div>',
            unsafe_allow_html=True)
    else:
        st.error('Silakan tambahkan lebih banyak teks. Teks terlalu pendek')
